import { expect, test } from '@playwright/test'

test('mobile core flow', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'NTU Life' })).toBeVisible()
  await page.getByRole('link', { name: /课表/ }).click()
  await page.getByRole('button', { name: '载入示例' }).click()
  await page.getByRole('button', { name: '确认导入' }).click()
  await expect(page.getByText('CA6000')).toBeVisible()
  await page.locator('.week-pills').getByRole('button', { name: 'W2' }).click()
  await expect(page.getByText('Week 2')).toBeVisible()
  await expect(page.getByText('17:00 - 19:00 · LT28').first()).toBeVisible()
  await page.locator('.week-pills').getByRole('button', { name: 'W9' }).click()
  await expect(page.getByText('Week 9')).toBeVisible()
  await expect(page.getByText('19:30 - 21:30 · LT28')).toBeVisible()
  await page.locator('.week-pills').getByRole('button', { name: 'W10' }).click()
  await expect(page.getByText('Week 10')).toBeVisible()
  await expect(page.getByText('19:30 - 21:30 · LT29')).toBeVisible()
  await page.locator('.week-pills').getByRole('button', { name: 'W12' }).click()
  await expect(page.getByText('Week 12')).toBeVisible()
  await expect(page.getByText('17:00 - 19:00 · LT2A')).toBeVisible()

  await page.getByRole('link', { name: /记账/ }).click()
  await page.getByRole('button', { name: '新增账目' }).click()
  await page.getByLabel('金额 SGD').fill('8')
  await page.getByLabel('备注').fill('打车')
  await page.getByRole('button', { name: '保存' }).click()
  await page.reload()
  await expect(page.getByText('打车')).toBeVisible()

  await page.getByRole('link', { name: /日程/ }).click()
  await page.getByRole('button', { name: '新建日程' }).click()
  await page.getByLabel('标题').fill('交作业')
  await page.getByRole('button', { name: '保存' }).click()
  await expect(page.getByText('交作业')).toBeVisible()

  await page.getByRole('link', { name: /设置/ }).click()
  const jsonDownloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出 JSON 备份' }).click()
  const jsonDownload = await jsonDownloadPromise
  expect(jsonDownload.suggestedFilename()).toBe('ntu-life-backup.json')
  const icsDownloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出日程 ICS' }).click()
  expect((await icsDownloadPromise).suggestedFilename()).toBe('ntu-life-agenda.ics')
  await expect(page.getByText('数据与导出')).toBeVisible()

  await page.evaluate(() => window.dispatchEvent(new Event('offline')))
  await expect(page.getByText(/离线模式/)).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
