import { expect, test } from '@playwright/test'

test('mobile core flow', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'NTU Life' })).toBeVisible()
  await expect(page.getByText('个人主页')).toBeVisible()

  await page.getByRole('link', { name: /课表/ }).click()
  await expect(page.locator('.week-pills').getByRole('button', { name: '第 1 周' })).toHaveClass(/active/)
  await page.getByRole('button', { name: '载入示例' }).click()
  await page.getByRole('button', { name: '确认导入' }).click()
  await expect(page.getByRole('button', { name: /CA6000/ }).first()).toBeVisible()
  await page.getByRole('button', { name: /CA6000 Online Video/ }).click()
  await expect(page.getByText('已完成')).toBeVisible()

  await page.locator('.week-pills').getByRole('button', { name: '第 2 周' }).click()
  await expect(page.getByRole('button', { name: /17:00-19:00/ }).first()).toBeVisible()
  await expect(page.getByRole('button', { name: /LT28/ }).first()).toBeVisible()
  await page.locator('.week-pills').getByRole('button', { name: '第 9 周' }).click()
  await expect(page.getByRole('button', { name: /LT28/ }).first()).toBeVisible()
  await page.locator('.week-pills').getByRole('button', { name: '第 10 周' }).click()
  await expect(page.getByRole('button', { name: /LT29/ }).first()).toBeVisible()
  await page.locator('.week-pills').getByRole('button', { name: '第 12 周' }).click()
  await expect(page.getByRole('button', { name: /LT2A/ }).first()).toBeVisible()

  await page.locator('.week-pills').getByRole('button', { name: '第 1 周' }).click()
  await page.getByRole('button', { name: /CA6000 20:00-22:00/ }).click()
  await expect(page.locator('.sheet-grabber')).toBeVisible()
  await expect(page.getByRole('link', { name: '打开 NTU Maps' })).toHaveAttribute('href', /search=/)
  await page.getByLabel('课程备注').fill('带电脑')
  await page.getByRole('button', { name: '保存' }).click()
  await expect(page.getByText('备注').first()).toBeVisible()

  await page.getByRole('link', { name: /记账/ }).click()
  await page.locator('.preset-grid').getByRole('button', { name: '交通', exact: true }).click()
  await page.getByLabel('金额').fill('8')
  await page.getByRole('button', { name: '保存' }).click()
  await page.locator('.preset-grid').getByRole('button', { name: '交通', exact: true }).click()
  await page.getByText('人民币', { exact: true }).click()
  await page.getByLabel('金额').fill('40')
  await page.getByRole('button', { name: '保存' }).click()
  await expect(page.getByText('今天支出')).toBeVisible()
  await expect(page.getByText('¥40.00 / S$8.00')).toBeVisible()
  await expect(page.getByText('S$48.00')).toHaveCount(0)
  await expect(page.getByText('每日支出')).toBeVisible()
  await expect(page.getByText('当天汇总')).toBeVisible()
  await expect(page.getByText('交通').first()).toBeVisible()
  await expect(page.getByText('结余')).toHaveCount(0)
  const quickExpensePanel = page.locator('section.panel').filter({ has: page.getByRole('heading', { name: '快捷消费' }) })
  await quickExpensePanel.getByRole('button', { name: '编辑' }).click()
  await expect(page.getByPlaceholder('新增快捷项，例如咖啡')).toBeVisible()
  await expect(page.locator('.mini-remove').first()).toContainText('删除')
  await quickExpensePanel.getByRole('button', { name: '完成' }).click()

  await page.getByRole('link', { name: /日程/ }).click()
  await page.getByRole('button', { name: '新建日程' }).click()
  await page.getByLabel('标题').fill('交作业')
  await page.getByRole('button', { name: '保存' }).click()
  await expect(page.getByText('交作业')).toBeVisible()

  await page.getByRole('link', { name: /首页/ }).click()
  await expect(page.getByText(/Applied AI Programming/)).toBeVisible()
  await expect(page.getByText('今日待办')).toBeVisible()
  await expect(page.getByText('交作业')).toBeVisible()
  await expect(page.getByText('今日支出')).toBeVisible()
  await expect(page.getByText('¥40.00 / S$8.00')).toBeVisible()

  await page.getByRole('link', { name: /设置/ }).click()
  const jsonDownloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出 JSON 备份' }).click()
  const jsonDownload = await jsonDownloadPromise
  expect(jsonDownload.suggestedFilename()).toBe('ntu-life-backup.json')
  const icsDownloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出日程 ICS' }).click()
  expect((await icsDownloadPromise).suggestedFilename()).toBe('ntu-life-agenda.ics')

  await page.getByText('English', { exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Settings' })).toBeVisible()
  await page.getByRole('link', { name: /Money/ }).click()
  await expect(page.getByRole('heading', { name: 'Money' })).toBeVisible()
  await expect(page.locator('section.panel').filter({ has: page.getByRole('heading', { name: 'Quick Expense' }) }).getByRole('button', { name: 'Edit' })).toBeVisible()
  await page.getByRole('link', { name: /Schedule/ }).click()
  await expect(page.getByRole('heading', { name: 'Schedule' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Import' })).toBeVisible()
  await page.getByRole('link', { name: /Agenda/ }).click()
  await expect(page.getByRole('heading', { name: 'Agenda' })).toBeVisible()
  await page.getByRole('link', { name: /Home/ }).click()
  await expect(page.getByText('Profile')).toBeVisible()

  await page.evaluate(() => window.dispatchEvent(new Event('offline')))
  await expect(page.getByText(/Offline mode/)).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
